apiVersion: v1
kind: Service
metadata:
  name: cloud-nav2-node # <- cloud-nav2-svc
  labels:
    app: cloud-nav2-node  # <- cloud-nav2-svc
    stage: pre-check
spec:
  type: NodePort
  selector:
    app: cloud-nav2
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    name: socket-test
  - protocol: TCP
    port: 25567
    targetPort: 25567
    name: nav2-p1
  - protocol: TCP
    port: 25568
    targetPort: 25568
    name: nav2-p2
  - protocol: TCP
    port: 25569
    targetPort: 25569
    name: nav2-p3
  - protocol: TCP
    port: 25570
    targetPort: 25570
    name: nav2-p4
